In [7]:
import numpy as np
a = np.array([1,2,3,4])
a.shape

(4,)

#### The concept of rows and columns applies when you have a 2D array. However, the array numpy.array([1,2,3,4]) is a 1D array and so has only one dimension, therefore shape rightly returns a single valued iterable.

>For a 2D version of the same array, consider the following instead:

In [11]:
a=np.array([[1,2,3,4]])
a
a.shape

(1, 4)

In [23]:
# We will represent vector as a column vector,that is having multiple rows and columns
x=np.array([[1],[2],[3],[4]])
print(x)
print(x.shape)#(4,1)--> 4 rows, 1 column
print(x[0])
print(x[0][0])
# print(x.reshape((-1,)))#
# x=x.reshape((-1,))
# print(x)
# print(x.shape)

[[1]
 [2]
 [3]
 [4]]
(4, 1)
[1]
1


In [32]:
print(x.reshape(2,2))
print(x)

[[1 2]
 [3 4]]
[[1]
 [2]
 [3]
 [4]]


In [35]:
x=np.array(np.arange(10))

So  -1 notation, what it does is the notation for unknown dimension, meaning: let numpy fill the missing dimension with the correct value so my array remain with the same number of items.

In [37]:
x.reshape(5,-1)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

### Tensors

![tensors](https://miro.medium.com/max/875/1*V83L4ydCdk21tXjP22VjXQ.jpeg)

###### A tensor is a container which can house data in N dimensions, along with its linear operations
* Often and erroneously used interchangeably with the matrix (which is specifically a 2-dimensional tensor), tensors are generalizations of matrices to N-dimensional space.
>Mathematically speaking, tensors are more than simply a data container, however. Aside from holding numeric data, tensors also include descriptions of the valid linear transformations between tensors. Examples of such transformations, or relations, include the cross product and the dot product. From a computer science perspective, it can be helpful to think of tensors as being objects in an object-oriented sense, as opposed to simply being a data structure.

#### Tensors often offer more natural representations of data, e.g., consider video, which consists of obviously correlated images over time

In [42]:
#Here T is a Tensor
X=np.array([[[4,5,7],[10,11,13]],[[1,2,3],[7,8,9]]])
print(X.shape)

(2, 2, 3)


### numpy.transpose

In [46]:
x=np.array([[1,2,3,4],[5,6,7,8]])
xt=np.transpose(x)
print(xt)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


### Visualizing matrix multiplication as a linear combination 
When multiplying two matrices, there's a manual procedure we all know how to go through. Each result cell is computed separately as the dot-product of a row in the first matrix with a column in the second matrix. While it's the easiest way to compute the result manually, it may obscure a very interesting property of the operation: multiplying A by B is the linear combination of A's columns using coefficients from B. Another way to look at it is that it's a linear combination of the rows of B using coefficients from A.


#### Right-multiplication: combination of columns
- Let's begin by looking at the right-multiplication of matrix X by a column vector:<br>
![title](https://eli.thegreenplace.net/images/math/ba570f74b122c0a20e4488a052b25fbda160c138.png)

<br>
- Representing the columns of X by colorful boxes will help visualize this:


![title](https://eli.thegreenplace.net/images/2015/veccomb.png)


Sticking the white box with a in it to a vector just means: multiply this vector by the scalar a. The result is another column vector - a linear combination of X's columns, with a, b, c as the coefficients.

Right-multiplying X by a matrix is more of the same. Each resulting column is a different linear combination of X's columns:<br>
![title](https://eli.thegreenplace.net/images/math/d6065791babbc5b967c06b57322711424097c83c.png)


![title](https://eli.thegreenplace.net/images/2015/matcomb.png)

#### Hadamard product
- __Hadamard Product__ is elementwise multiplication and it outputs a vector.
- Values that correspond positionally are multiplied to produce a new matrix.

In [56]:
a = np.array(
[[2,3],
 [2,3]])
b = np.array(
[[3,4],
 [5,6]])

# Uses python's multiply operator
a * b #(Hadamard Operator)


array([[ 6, 12],
       [10, 18]])

### Norms
###### Defining L¹ & L² Norms (and Beyond!)
- The L¹ and L² norms are commonly used for assigning a magnitude to a vector. For a vector x having N components, the L¹ just adds up the components. Since we would like our magnitude to always be positive, we take the absolute value of the components.


![title](https://cdn-images-1.medium.com/max/1200/1*UY2EEP_f7DC0BJsoM2Eqjg.png)

- The L² norm takes the sum of the squared values, taking the square root at the end. The L² norm is the same as a standard distance formula, which finds the shortest path from A to B.

![title](https://cdn-images-1.medium.com/max/1200/1*ccWm-HBA85UnnFiWrFwvsg.png)

- if you start to see a pattern, then you might ask: Why stop at 2? We can create a norm for all 1 ≤ p < ∞ in this way too!
![title](https://cdn-images-1.medium.com/max/1200/1*raXsqlpSn8RFLhDGWOKQnA.png)



   - Norms are 0 if and only if the vector is a zero vector
   - Norms respect the triangle inequity.
   -  ∥k⋅u∥=|k|⋅∥u∥. The norm of a vector multiplied by a scalar is equal to the absolute value of thisscalar multiplied by the norm of the vector.

__Max Norm__: the largest absolute value of the element in the vector, which can be written as:
![title](https://cdn-images-1.medium.com/max/1000/1*x5iqiil6pZWETrQP3VBa3Q.png)

In [61]:
m=np.array([-4,2,6])

In [64]:
lp2=np.linalg.norm(m)
lp2

7.483314773547883

In [66]:
lp1=np.linalg.norm(m,ord=1)
lp1

12.0

In [69]:
lpinf=np.linalg.norm(m,ord=np.inf)
lpinf

6.0

<img src="images/fnorm.png" alt="Drawing" style="width: 310px;"/>


<img src="images/matrix norms.png" alt="Drawing" style="width: 510px;"/>


In [8]:
q2=np.array([[2,-2,1],[-1,2,-1],[2,-4,1]])

In [9]:
q2

array([[ 2, -2,  1],
       [-1,  2, -1],
       [ 2, -4,  1]])

In [15]:
np.linalg.norm(q2,ord=2)

5.9287221489704836

In [16]:
np.linalg.norm(q2,'fro')

6.0

In [17]:
np.linalg.norm(q2)# it calculates frobenius norm

6.0

#### In case of matrices,np.linalg.norm(__matrix__) by default gives Frobenius norm	

L2 norm and Frobenius norm	are different for matrices. Frobenius norm	is similar to L2 norm of a vector


In [23]:
A=np.array([[1,-3,4],[-2,10,-7],[0,1,0],[0,0,0]])
B=np.array([[5,0],[-2,11],[-3,12]])
print(A)
print(B)

[[ 1 -3  4]
 [-2 10 -7]
 [ 0  1  0]
 [ 0  0  0]]
[[ 5  0]
 [-2 11]
 [-3 12]]


In [22]:
A.dot(B)

array([[-1, 15],
       [-9, 26],
       [-2, 11],
       [ 0,  0]])